package com.badbones69.blockparticles.api.enums;

public enum BPParticles {
    
    LOVE_WELL(),
    BIG_LOVE_WELL(),
    LOVE_TORNADO(),
    WITCH_TORNADO(),
    FLAME_WHEEL(),
    SOUL_WELL(),
    BIG_SOUL_WELL(),
    SANTA_HAT(),
    SNOW_BLAST(),
    RAINBOW(),
    ENDER_SIGNAL(),
    MOB_SPAWNER(),
    ANGRY_VILLAGER(),
    HAPPY_VILLAGER(),
    FOOTPRINT(),
    FIRE_SPEW(),
    SNOWSTORM(),
    DOUBLE_WITCH(),
    WITCH(),
    MAGIC(),
    SPEW(),
    HALO(),
    MUSIC(),
    POTION(),
    SNOW(),
    FIRESTORM(),
    WATER(),
    CHAINS(),
    ENCHANT(),
    FOG(),
    STORM(),
    BIG_FLAME(),
    FLAME(),
    VOLCANO(),
    SPIRAL(),
    DOUBLE_SPIRAL(),
    CRIT(),
    BIG_CRIT();
    
}