name: '${name}'

main: '${group}.${name}'

authors: ${authors}

version: '${version}'
api-version: '${apiVersion}'
description: '${description}'
website: '${website}'

commands:
  bp:
    description: A test command for particles